# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

include: ['_pages']

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap