# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge

collections:
  - publications

include: ['_pages']

plugins:
  - jekyll-sitemap