# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

permalink: /blog/:categories/:title

# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

include: ['_pages', '_rss']

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  papers:
    defaults:
      layout: academic
    output: true
    permalink: /papers/:path/
  news:
    defaults:
      layout: academic
    output: true
    permalink: /news/:path

news_limit: 5
