# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

permalink: /blog/:categories/:title

# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

include: ['_pages']

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: academic
    output: true
    permalink: /news/:path

news_limit: 5
