# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  blog:
    output: true
    permalink: /blog/:path/
  projects:
    output: true
    permalink: /projects/:path/
  linkedin:
    output: true
    permalink: /linkedin/:path/

include: ['_pages']

plugins:
  - jekyll-sitemap