# -----------------------------------------------------------------------------
# Jekyll
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge

collections:
  blog:
    output: true
    permalink: /blog/:path/
  projects:
    output: true
    permalink: /projects/:path/

include: ['_pages']

plugins:
  - jekyll-sitemap